name: Make RSS Feed

on:
  schedule:
    - cron: '18 1 * * *'
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run python script
        run: python main.py

      - name: Commit changes
        run: |
          git config --global user.name 'Gitub Action'
          git config --global user.email 'action@github.com'
          git add schedule.json
          git commit -m "automated commit"
          git push